# turned out there was a bug in my original implemention
# it was just fixed here no reason to use re previous script now
# Note that all of this code was still generated by AI and I'm not going to pretend it isn't
# but it isn't exactly relevant

from unidecode import unidecode
from pprint import pprint
from datetime import datetime, timedelta, time, date
from dataclasses import dataclass, field
from typing import Dict, List, Set, Tuple, Optional
import json
import math
import random


random.seed(12345)

# Parameters that can be adjusted to change generation rules; They not always as straight forward as their name might suggest

FILES = ["input/m_names.csv", "input/f_names.csv", "input/m_lastnames.csv", "input/f_lastnames.csv"]
MAJORS_PATH = "input/majors.json"
NUM_OF_WORKERS = 800
OUTPUT_FILE = "data.sql"
STUDENTS_PER_GROUP = 15
SEX = [("M", 0.49), ("F", 0.49), ("O", 0.02)]

NULL_TELEPHONE_CHANCE = 0.2
NULL_SEX_CHANCE = 0.01
NULL_WORKER_FACULTY_CHANCE = 0.25

STUDENT_DECAY = [1.0, 0.85, 0.80, 0.80, 0.75, 0.70, 0.65]
MAJOR_SIZES = ([45, 60, 100, 120, 150, 200], [0.15, 0.15, 0.25, 0.25, 0.1, 0.1])
ECTS_DISTRIBUTION =(
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [0.02, 0.03, 0.1, 0.2, 0.25, 0.25, 0.05, 0.05, 0.03, 0.02]
)

DOUBLE_MAJOR_CHANCE = 0.07
TRIPLE_MAJOR_CHANCE = 0.02
QUAD_MAJOR_CHANCE = 0.006

EMAIL_DOMAIN = "agh.edu.pl"
USED_DAYS = [1, 2, 3, 4, 5]
START_DATES = [ 
    datetime(2025, 10, 1),
    datetime(2025, 11, 1),
    datetime(2026,  3, 1),
    datetime(2026,  4, 1),
]

END_DATES = [   
    datetime(2026,  1, 31),
    datetime(2026,  2, 28),
    datetime(2026,  5, 31),
    datetime(2026,  6, 30) 
]

# Class that stores generation of some unique values like emails and phone numbers
# @dataclass is used to automatically create some useful methods like __init__
@dataclass
class UniqueGenerators:
    # those store already used ones
    telephones: Set[str] = field(default_factory=set)
    emails: Set[str] = field(default_factory=set)
    codes: Set[str] = field(default_factory=set)

    def generate_phone(self) -> Optional[str]:
        # phone can be NULL
        if random.random() < NULL_TELEPHONE_CHANCE:
            return None

        number = "".join(str(random.randint(0, 9)) for _ in range(9))
        phone = f"+48{number}"

        # repeat until unique
        while phone in self.telephones:
            number = "".join(str(random.randint(0, 9)) for _ in range(9))
            phone = f"+48{number}"

        self.telephones.add(phone)
        return phone

    def generate_email(self, first_name: str, last_name: str) -> str:
        # we want to get rid of polish chars and also convert to lowercase first
        base = f"{unidecode(first_name.lower())}_{unidecode(last_name.lower())}"
        number = "".join(str(random.randint(0, 9)) for _ in range(3))
        email = f"{base}{number}@{EMAIL_DOMAIN}"

        # repeat until unique
        while email in self.emails:
            number = "".join(str(random.randint(0, 9)) for _ in range(3))
            email = f"{base}{number}@{EMAIL_DOMAIN}"

        self.emails.add(email)
        return email

    def generate_code(self, prefix: str, suffix: str = "") -> str:
        # some code are extended other codes
        # it simply concatenates prefix, suffix and some random integers
        code = f"{prefix}{suffix}{''.join(str(random.randint(0, 9)) for _ in range(3))}"

        while code in self.codes:
            code = f"{prefix}{suffix}{''.join(str(random.randint(0, 9)) for _ in range(3))}"

        self.codes.add(code)
        return code


# this one is used to avoid schedule overlaps so it stores some relevant data
@dataclass
class ScheduleSlot:
    # I assumed for the sake of generation that we don't have classes that take only half of a semester
    # But DB does support them and frankly It's not a big deal as we can just use random start and end dates when generating
    day_of_week: int
    start_date: date
    end_date: date
    start_time: time
    end_time: time
    major: int
    semester: int
    cohort: int # used for student assignment
    is_lecture: bool

    # Note the is_multi_major flag; It's needed as different logic must be used for fro multi_major students
    def overlaps_with(self, other: 'ScheduleSlot', is_multi_major: bool = False ) -> bool:
        if self.day_of_week != other.day_of_week:
            return False

        if is_multi_major == False:
            if self.major != other.major or self.semester != other.semester:
                return False

            # lectures are special type that is assumed to not belong to any cohort
            if not (self.is_lecture or other.is_lecture or self.cohort == other.cohort):
                return False

        return (
            self.start_time <= other.end_time and other.start_time <= self.end_time and
            self.start_date <= other.end_date and other.start_date <= self.end_date
        )

    # needed to store objects in a set
    def __hash__(self):
        return hash((self.day_of_week, self.major, self.semester))


# loads data from files
class DataLoader:
    @staticmethod
    # Load CSV with name,weight format.
    def load_weighted_data(filepath: str) -> List[Tuple[str, float]]:
        data = []
        with open(filepath, encoding="utf-8") as fh:
            for line in fh:
                parts = line.strip().split(",")
                data.append((parts[0], float(parts[1])))
        return data

    @staticmethod
    # loads all names and last name files
    def load_names() -> Dict[str, List[Tuple[str, float]]]:
        return {
            'M_NAMES': DataLoader.load_weighted_data(FILES[0]),
            'F_NAMES': DataLoader.load_weighted_data(FILES[1]),
            'M_LASTNAMES': DataLoader.load_weighted_data(FILES[2]),
            'F_LASTNAMES': DataLoader.load_weighted_data(FILES[3]),
        }

    @staticmethod
    # loads JSON with majors
    def load_majors(filepath: str) -> Dict:
        with open(filepath, encoding="utf-8") as fh:
            return json.load(fh)


# Main class used for data generation
class DatabaseGenerator:
    def __init__(self):
        # previous data needed in generation
        self.unique_gen = UniqueGenerators()
        self.names = DataLoader.load_names()
        self.majors = DataLoader.load_majors(MAJORS_PATH)

        # Tracking of data used throughout the generation
        self.faculties: Dict[str, int] = {}
        self.faculties_to_workers: Dict[int, List[int]] = {}
        self.instructor_schedule: Dict[int, List[Tuple[date, date, time, time, int]]] = {}
        self.groups: Set[ScheduleSlot] = set()
        self.group_data: List[Dict] = []
        self.students_to_courses: Dict[int, Set[Tuple[int, date, date]]] = {}
        self.num_students = 0

    # generates data used both for workers and students
    def generate_person(self) -> Dict:
        sex = random.choices([s[0] for s in SEX], weights=[s[1] for s in SEX], k=1)[0]
        # sex can be null
        if random.random() < NULL_SEX_CHANCE:
            sex = None

        # Select appropriate name lists
        if not sex or sex == "O":
            name_list = random.choice([self.names['M_NAMES'], self.names['F_NAMES']])
            last_list = random.choice([self.names['M_LASTNAMES'], self.names['F_LASTNAMES']])
        elif sex == "F":
            name_list = self.names['F_NAMES']
            last_list = self.names['F_LASTNAMES']
        else:
            name_list = self.names['M_NAMES']
            last_list = self.names['M_LASTNAMES']

        # generate with probablites
        first_name = random.choices(*zip(*name_list))[0]
        last_name = random.choices(*zip(*last_list))[0]

        # dict with person info
        return {
            'first_name': first_name,
            'last_name': last_name,
            'sex': sex,
            'telephone': self.unique_gen.generate_phone(),
            'email': self.unique_gen.generate_email(first_name, last_name)
        }

    def create_faculties(self) -> List[Dict]:
        faculties = []
        # first ID is 1
        faculty_id = 1

        # add all faculties that exist in json with Majors
        for major_info in self.majors.values():
            faculty_name = major_info["faculty"]
            if faculty_name not in self.faculties:
                # adding faculty to internal dict as well
                self.faculties[faculty_name] = faculty_id

                faculties.append({
                    "faculty_id": faculty_id,
                    "name": faculty_name,
                    "dean_worker_id": random.randint(1, NUM_OF_WORKERS),  # Updated later
                })
                faculty_id += 1

        return faculties

    def create_majors(self) -> List[Dict]:
        majors = []

        for idx, (major_name, major_info) in enumerate(self.majors.items(), 1):
            # generate code for the major in form: MAJ-123
            code = self.unique_gen.generate_code(major_name[:3].upper() + "-")

            majors.append({
                "major_id": idx,
                "name": major_name,
                "code": code,
                "faculty_id": self.faculties[major_info["faculty"]],
            })

            # Update the dict that stores data from majos.json for later use
            major_info["code"] = code
            major_info["id"] = idx

        return majors

    def create_courses(self) -> List[Dict]:
        courses = []
        course_id = 1

        for _, major_info in self.majors.items():
            # random number of students based on probabilities above
            student_count = random.choices(*MAJOR_SIZES)[0]

            for sem_idx, semester in enumerate(major_info["semesters"]):
                # students decay over time
                semester_students = int(student_count * STUDENT_DECAY[sem_idx])
                # update fro later use
                semester["student_count"] = semester_students

                for course_idx, course_title in enumerate(semester["courses"]):
                    # generate code in form MAJ-123-COU-456
                    # so major code is needed here
                    code = self.unique_gen.generate_code(
                        f"{major_info['code']}-{course_title[:3].upper()}-"
                    )

                    # also random based on probabilities above
                    ects = random.choices(*ECTS_DISTRIBUTION)[0]

                    courses.append({
                        "course_id": course_id,
                        "title": course_title,
                        "code": code,
                        "major_id": major_info["id"],
                        "ects_credits": ects,
                    })

                    # Also useful later
                    semester["courses"][course_idx] = {
                        "title": course_title,
                        "code": code,
                        "id": course_id,
                        # note that this is what actually determines number of students
                        "group_count": math.ceil(semester_students / STUDENTS_PER_GROUP),
                    }
                    course_id += 1

        return courses

    def create_workers(self) -> List[Dict]:
        workers = []
        self.faculties_to_workers = {fid: [] for fid in self.faculties.values()}

        for worker_id in range(1, NUM_OF_WORKERS + 1):
            person = self.generate_person()
            # assign to random faculty
            faculty_id = random.randint(1, len(self.faculties))
            if random.random() < NULL_WORKER_FACULTY_CHANCE:
                faculty_id = None

            worker = {
                "worker_id": worker_id,
                # include all the person data
                **person,
                "faculty_id": faculty_id,
                # be default none are teaching
                "teaching": False,
            }

            workers.append(worker)

            # used to choose appropriate workers when creating groups
            if faculty_id:
                self.faculties_to_workers[faculty_id].append(worker_id)
                # used to check if instructor schedule doesn't overlap
                self.instructor_schedule[worker_id] = []

        return workers

    # choose dean for each faculty that actually belongs to this faculty
    def update_deans(self, faculties: List[Dict]) -> List[Dict]:
        for faculty in faculties:
            faculty["dean_worker_id"] = random.choice(
                self.faculties_to_workers[faculty["faculty_id"]]
            )
        return faculties

    # returns intervals at which courses start and end
    def generate_time_slots(self, start_hour=8, end_hour=20, lesson_min=90, break_min=15) -> List[Tuple[time, time]]:
        slots = []
        # date unimportant
        current = datetime(2000, 1, 1, start_hour, 0)
        lesson_delta = timedelta(minutes=lesson_min)
        break_delta = timedelta(minutes=break_min)
        end_time = time(hour=end_hour, minute=0)

        # just iterate adding lesson_min and break_min alternately
        while current.time() <= end_time:
            slot_end = current + lesson_delta
            if slot_end.time() > end_time:
                break

            # convert to nice format
            slots.append((
                current.time(),
                slot_end.time()
            ))
            current = slot_end + break_delta

        return slots

    # we want to find instructor that belongs to given faculty and is not already assigned to some group and given time
    def find_available_instructor(self, day: int, start_date: date, end_date: date, start_time: time, end_time: time, faculty_id: int) -> int:
        workers = self.faculties_to_workers[faculty_id]
        max_attempts = len(workers) * 2

        for _ in range(max_attempts):  # Limit attempts
            instructor = random.choice(workers)

            # Check for conflicts
            has_conflict = any(
                existing_day == day and
                not (end_date <= existing_start_date or existing_end_date <= start_date) and
                not (end_time <= existing_start_time or  existing_end_time <= start_time)
                for existing_start_date, existing_end_date, existing_start_time, existing_end_time, existing_day 
                # list of tuples (start-time, end-time, week-day)
                in self.instructor_schedule[instructor]
            )

            # add to schedule
            if not has_conflict:
                self.instructor_schedule[instructor].append((start_date, end_date, start_time, end_time, day))
                return instructor

        raise RuntimeError(f"Could not find instructor after {max_attempts} attempts; Consider increasing number of instructors")

    def create_groups(self) -> List[Dict]:
        time_slots = self.generate_time_slots()
        group_id = 1

        # lectures and groups are created seperately as lectures overlap with all exercise groups
        for _, major_info in self.majors.items():
            for semester in major_info["semesters"]:
                # Lectures first
                for course in semester["courses"]:
                    group_id = self._create_group_with_retry(
                        group_id, course, semester["semester"], major_info["id"], self.faculties[major_info["faculty"]],
                        is_lecture=True, cohort=-1,
                        time_slots=time_slots, days=USED_DAYS
                    )

                # Then exercises
                for course in semester["courses"]:
                    for cohort in range(1, course["group_count"] + 1):
                        group_id = self._create_group_with_retry(
                            group_id, course, semester["semester"], major_info["id"], self.faculties[major_info["faculty"]],
                            is_lecture=False, cohort=cohort,
                            time_slots=time_slots, days=USED_DAYS
                        )

        return self.group_data

    def _get_start_end_date_pair(self):
        start_date = random.choice(START_DATES)
        end_date = random.choice([date for date in END_DATES if date > start_date])
        return start_date, end_date

    # create group, retrying if schedule conflicts exist.
    # return new group_id
    def _create_group_with_retry(self, group_id: int, course: dict, semester: int, major_id: int, faculty_id: int, 
                                 is_lecture: bool, cohort: int, time_slots: List[Tuple[time, time]], days: List[int]) -> int:
        # don't generate infinetely
        max_attempts = 500

        for _ in range(max_attempts):
            day = random.choice(days)
            start_time, end_time = random.choice(time_slots)
            start_date, end_date = self._get_start_end_date_pair()

            # used to check for overlap
            slot = ScheduleSlot(
                day_of_week=day,
                start_date=start_date,
                end_date=end_date,
                start_time=start_time,
                end_time=end_time,
                major=major_id,
                semester=semester,
                cohort=cohort,
                is_lecture=is_lecture
            )

            # Check for conflicts with any group
            if not any(slot.overlaps_with(existing) for existing in self.groups):
                self.groups.add(slot)

                # generate code in from MAJ-123-COU-456-WYK/CWI-789
                code_suffix = "-WYK-" if is_lecture else "-CWI-"
                code = self.unique_gen.generate_code(course["code"], code_suffix)

                # get instructor
                instructor = self.find_available_instructor(
                    day, start_date, end_date, start_time, end_time, faculty_id
                )

                # all data for required for groups
                self.group_data.append({
                    "group_id": group_id,
                    "course_id": course["id"],
                    "instructor_worker_id": instructor,
                    "code": code,
                    "day_of_week": day,
                    "start_date": start_date,
                    "end_date": end_date,
                    "start_time": start_time,
                    "end_time": end_time,
                    "_is_lecture": is_lecture,
                    "_cohort": cohort,
                    "_major": major_id,
                    "_semester": semester,
                    "_slot": slot
                })

                return group_id + 1

        raise RuntimeError(f"Could not schedule group after {max_attempts} attempts")

    # return all groups that have the same cohort number and belong to the same major and semester
    def get_cohort_groups(self, major_id: int, semester: int, cohort: int) -> List[Dict]:
        cohort_groups = []
        for group in self.group_data:
            if group["_major"] == major_id and group["_semester"] == semester:
                if group["_is_lecture"] or group["_cohort"] == cohort:
                    cohort_groups.append(group)
        return cohort_groups

    # assign students to group and majors
    # this is a single assign (one student to one group)
    # students are first assigend and then created 
    def assign_students(self) -> Tuple[List[Dict], List[Dict]]:
        students_to_majors = []
        students_to_groups = []
        student_id = 1

        # all groups in a cohort
        self.cohort_groups = {}

        for group in self.group_data:
            if not group["_is_lecture"]:
                key = (group["_major"], group["_semester"], group["_cohort"])
                if key not in self.cohort_groups:
                    self.cohort_groups[key] = []
                self.cohort_groups[key].append(group)

        # Add lectures to cohorts
        for group in self.group_data:
            if group["_is_lecture"]:
                major_id, semester = group["_major"], group["_semester"]
                for key in self.cohort_groups:
                    if key[0] == major_id and key[1] == semester:
                        self.cohort_groups[key].append(group)

        # Assign students to cohorts
        for cohort_key, groups in self.cohort_groups.items():
            if cohort_key[2] == -1:  # Skip lecture-only entries
                continue

            # add some additional randomndess idk why
            num_students = random.randint(STUDENTS_PER_GROUP - 3, STUDENTS_PER_GROUP + 1)

            for _ in range(num_students):
                self._assign_student_to_cohort(student_id, groups, students_to_majors, students_to_groups)
                student_id += 1

        # update the number of students that will be created later
        self.num_students = student_id
        return students_to_majors, students_to_groups

    def _assign_student_to_cohort(self, student_id: int, groups: List[Dict], students_to_majors: List[Dict], students_to_groups: List[Dict]) -> None:
        if student_id not in self.students_to_courses:
            # used later to create marks
            self.students_to_courses[student_id] = set()

        # enroll in all courses in the cohort
        for group in groups:
            if group['_is_lecture'] == False:
                self.students_to_courses[student_id].add((group["course_id"], group["start_date"], group["end_date"]))

            students_to_groups.append({
                "student_id": student_id,
                "group_id": group["group_id"]
            })

        # record student's major-semester mapping
        students_to_majors.append({
            "student_id": student_id,
            "major_id": groups[0]["_major"],
            "semester": groups[0]["_semester"],
        })

        # we want to simulate some students being assigned to more than one major
    def add_multi_major_students(self, students_to_majors: List[Dict], students_to_groups: List[Dict]) -> Tuple[List[Dict], List[Dict]]:
        print(f"Initial student count: {self.num_students - 1}")

        double_major_count = int(DOUBLE_MAJOR_CHANCE * self.num_students)
        triple_major_count = int(TRIPLE_MAJOR_CHANCE * self.num_students)
        quad_major_count = int(QUAD_MAJOR_CHANCE * self.num_students)

        print(f"Adding {double_major_count} double-major and {triple_major_count} triple-major and {quad_major_count} quad-major students")


        cohort_list = list(self.cohort_groups.values())

        # add double-major students
        for _ in range(double_major_count):
            groups = self._find_non_conflicting_cohorts(2, cohort_list)
            if groups:
                self._assign_multi_major_student(groups, students_to_majors, students_to_groups)

        # add triple-major students
        for _ in range(triple_major_count):
            groups = self._find_non_conflicting_cohorts(3, cohort_list)
            if groups:
                self._assign_multi_major_student(groups, students_to_majors, students_to_groups)

        # add quadruple-major students
        for _ in range(triple_major_count):
            groups = self._find_non_conflicting_cohorts(4, cohort_list)
            if groups:
                self._assign_multi_major_student(groups, students_to_majors, students_to_groups)

        print(f"Final student count: {self.num_students - 1}")
        return students_to_majors, students_to_groups

    def _find_non_conflicting_cohorts(self, count: int, all_cohorts: List[Dict]) -> Optional[List[Dict]]:
        max_attempts = 500  
        for _ in range(max_attempts):
            random.shuffle(all_cohorts)

            # used for checks
            selected_cohort_slots = []
            selected_majors = set()
            # returned
            selected_cohort_groups = []

            for cohort in all_cohorts:
                major_id = cohort[0]["_major"]

                # cannot assign to the sam major twice
                if major_id in selected_majors:
                    continue

                has_conflict = any(
                    group["_slot"].overlaps_with(existing_slot, is_multi_major=True) # need to set this flag as those groups are only check by time/date
                    for group in cohort
                    for existing_slot in selected_cohort_slots
                )

                if not has_conflict:
                    selected_cohort_groups.extend(cohort)
                    selected_cohort_slots.extend([group['_slot'] for group in cohort])
                    selected_majors.add(major_id)

                    if len(selected_majors) == count:
                        return selected_cohort_groups

        # if we exit the loop, no non-conflicting set was found in the attempts
        print(f"Warning: Could not find {count} non-conflicting cohorts after {max_attempts} attempts. Skipping one student.")
        return None

    def _assign_multi_major_student(self, groups: List[Dict], students_to_majors: List[Dict], students_to_groups: List[Dict]):
        # first student to be assigned
        student_id = self.num_students

        # used for marks later
        if student_id not in self.students_to_courses:
            self.students_to_courses[student_id] = set()

        # used for assigning to majors
        # contains a tuples (major_id, semester)
        majors = set()

        # enroll in all courses across all cohorts
        for group in groups:
            if group['_is_lecture'] == False:
                self.students_to_courses[student_id].add((group["course_id"], group["start_date"], group["end_date"]))
            majors.add((group["_major"], group["_semester"]))

            students_to_groups.append({
                "student_id": student_id,
                "group_id": group["group_id"]
            })

        # add one major record per cohort
        for major in majors:
            students_to_majors.append({
                "student_id": student_id,
                "major_id": major[0],
                "semester": major[1]
            })

        self.num_students += 1 

    # students don
    def create_students(self) -> List[Dict]:
        return [
            {
                "student_id": i + 1, 
                **self.generate_person()
            }
            for i in range(self.num_students - 1)
        ]

    def create_marks(self) -> List[Dict]:
        """Generate marks for students."""
        marks = []
        mark_id = 1
        # used for checks
        today = datetime.today()

        for student_id, courses in self.students_to_courses.items():
            for course_id, start_date, end_date in courses:

                # if course haven't started yet cannot add any marks
                if start_date > today:
                    continue

                # as above don't add marks to dates that haven't happened yet
                end_date = min(datetime.today(), end_date)
                days_range = (end_date - start_date).days

                # just a random number of marks
                for _ in range(random.randint(0, 4)):
                    marks.append({
                        "mark_id": mark_id,
                        "student_id": student_id,
                        "course_id": course_id,
                        "mark": random.randint(2, 5),
                        "weight": random.randint(1, 4),
                        "added": start_date + timedelta(days=random.randint(0, days_range))
                    })
                    mark_id += 1
        return marks

    # update the ones that are actually teaching
    def update_teaching_flags(self, workers: List[Dict]) -> List[Dict]:
        for worker in workers:
            if worker["faculty_id"]:
                worker["teaching"] = len(self.instructor_schedule[worker["worker_id"]]) > 0
        return workers

    # just generate all
    def generate_all(self) -> Dict[str, List[Dict]]:
        print("Generating faculties...")
        faculties = self.create_faculties()

        print("Generating majors...")
        majors = self.create_majors()

        print("Generating courses...")
        courses = self.create_courses()

        print("Generating workers...")
        workers = self.create_workers()
        faculties = self.update_deans(faculties)

        print("Scheduling groups...")
        groups = self.create_groups()

        print("Assigning students to cohorts...")
        students_to_majors, students_to_groups = self.assign_students()

        print("Adding multi-major students...")
        students_to_majors, students_to_groups = self.add_multi_major_students(
            students_to_majors, students_to_groups
        )

        print(f"Creating {self.num_students - 1} student records...")
        students = self.create_students()

        print("Updating worker teaching status...")
        workers = self.update_teaching_flags(workers)

        print("Generating marks...")
        marks = self.create_marks()

        # clean up internal fields from groups
        for group in groups:
            for key in list(group.keys()):
                if key.startswith('_'):
                    del group[key]

        return {
            "faculties": faculties,
            "majors": majors,
            "courses": courses,
            "workers": workers,
            "students": students,
            "groups": groups,
            "students_to_majors": students_to_majors,
            "students_to_groups": students_to_groups,
            "marks": marks,
        }


def format_sql_value(value) -> str:
    # turn some python types into SQL types
    if value is None:
        return "\\N"
    if isinstance(value, bool):
        return "t" if value else "f"
    if isinstance(value, (datetime, date)):
        return value.date().isoformat() if isinstance(value, datetime) else value.isoformat()
    if isinstance(value, time):
        return value.isoformat()
    return str(value)


# print data into file in correct structure
def write_copy_statement(data: List[Dict], table_name: str, file_handle, id_column: Optional[str] = None):
    if not data:
        return

    count = 0
    columns = ", ".join(data[0].keys())
    first_line = f"COPY {table_name} ({columns}) FROM stdin;\n"
    print(first_line)
    file_handle.write(first_line)

    for row in data:
        values = "\t".join(format_sql_value(row[col]) for col in row.keys())
        print([format_sql_value(row[col]) for col in row.keys()])  # Match original debug output
        file_handle.write(f"{values}\n")
        count += 1

    file_handle.write("\\.\n")

    # reset sequence if id_column specified
    if id_column:
        file_handle.write(f"SELECT setval('{table_name}_{id_column}_seq', {count}, true);")

    file_handle.write("\n\n")


def write_sql_file(data: Dict[str, List[Dict]], output_path: str):
    # names of tables and primary keys
    table_configs = [
        ("faculties", "faculty_id"),
        ("majors", "major_id"),
        ("courses", "course_id"),
        ("workers", "worker_id"),
        ("students", "student_id"),
        ("groups", "group_id"),
        ("students_to_majors", None),
        ("students_to_groups", None),
        ("marks", "mark_id"),
    ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("BEGIN;\n\n")

        for table_name, id_column in table_configs:
            print(f"Writing {table_name}...")
            write_copy_statement(data[table_name], table_name, f, id_column)

        f.write("\nCOMMIT;\n")

    print(f"\nSQL file written to: {output_path}")


def main():
    print("Starting database generation...")
    generator = DatabaseGenerator()
    data = generator.generate_all()
    write_sql_file(data, OUTPUT_FILE)
    print("Complete!")

if __name__ == "__main__":
    main()
